### ISSUE TITLE
Variable width using Grid Util

### ISSUE THREAD

**Issue by rafpaal** [grafana/grafonnet#52]
I've been trying to set a dashboard with panels with different sizes for some panels using the util.grid.makeGrid() function.

```
+ g.dashboard.withPanels(
  g.util.grid.makeGrid([
    row.new('Metrics')
    + row.withPanels([
      panels.time_series.base('Service Latency', queries.service_latency),
      panels.time_series.base('Endpoint Rate by Service', queries.endpoint_rate_by_service),
      panels.time_series.base('Error Rate', queries.error_rate),
      panels.bar_gauge.base('Top 5 Operations by Rate', queries.top_operations_by_rate),
    ]),
  ] panelWidth=12 )
  + g.util.gird.makeGrid([
    row.new('Node Graph')
    + row.withPanels([
      panels.node_graph.base('Node Graph',queries.node_graph),
    ]),
    row.new('Logs')
    + row.withPanels([
      panels.logs.base('Logs', queries.logs),
    ]),
    row.new('JVM'),
  ], panelWidth=24)
)
```

I thought that it would work doing something like that but that just scatters all of the panels rather changing the width. I also tried to add the width directly to the panels but seems like the makeGrid() function overrides the values.

I also tried adding them directly as an array like so

```
+ g.dashboard.withPanels([
    row.new('Metrics')
    + row.withPanels([
      panels.time_series.base('Service Latency', queries.service_latency),
      panels.time_series.base('Endpoint Rate by Service', queries.endpoint_rate_by_service),
      panels.time_series.base('Error Rate', queries.error_rate),
      panels.bar_gauge.base('Top 5 Operations by Rate', queries.top_operations_by_rate),
    ])
    + row.gridPos.withW(24)
    + row.gridPos.withH(8),
    row.new('Node Graph')
    + row.withPanels([
      panels.node_graph.base('Node Graph',queries.node_graph),
    ])
    + row.gridPos.withW(24)
    + row.gridPos.withH(8),
    row.new('Logs')
    + row.withPanels([
      panels.logs.base('Logs', queries.logs),
    ])
    + row.gridPos.withW(24)
    + row.gridPos.withH(8),
    row.new('JVM'),
  ]
)
```
```
  base(title, targets):
      nodeGraph.new(title)
      + nodeGraph.withTargets(targets)
      + nodeGraph.withDatasource('$' + variables.tempo_datasource.name)
      + nodeGraph.gridPos.withW(24)
      + nodeGraph.gridPos.withH(8)
```
      
But for some reason once they get imported to Grafana the panels get dropped and if I left the timeSeries panels in the definition the dashboard fails to initialize. 

Is there a correct way of achieving that?

**Comment by Duologic** [comment]
`makeGrid` doesn't consider being added twice, regardless of the sizes I think this will always fail to render properly. The function attempts to calculate the XY on the grid and always starts at zero (X=0, Y=0). Because of this, the second time `makeGrid` is called, it starts again at Y=0, messing up the layout. With other words, the `makeGrid` function is very naive and assumes it manages all panels in a dashboard, any other panels added after the first would need to take that into account. It would be interesting to consider different layout strategies to aid in more complex layouts like you are proposing.

On the second part, I can say: Rows are a bit weird in Grafana. :) When a row is collapsed, Grafana stores the panels below that row in the Row JSON object (row.withPanels) but when a row gets expanded, Grafana will move those panels and put them in the Dashboard JSON object (dashboard.withPanels) and recalculate the XY. This is annoying and needs to be taken into account when developing dashboards. `makeGrid` does an attempt at repeating that logic, it might be interesting to move that logic into a separate function so that it can also be applied elsewhere. It would also be necessary if we'd figure out different layout strategies.

I don't have a direct solution for your specific problems right now, but it's certainly something that we need to consider.

**Comment by rafpaal** [comment]
Got it, that makes sense. I guess I'll leave the panels for now as they are and maybe change them in the future. Thanks for the explanation :)

**Comment by Duologic** [comment]
I'd like to keep this issue open as a starting point for improving the Grid util, this issue has very useful feedback.

**Comment by albertteoh** [comment]
I also have a requirement for varying widths and so tried `makeGrid` twice:

```
+ g.dashboard.withPanels(
  g.util.grid.makeGrid(
    [
      row.new("Row 1")
      + row.withPanels([
        panels.timeSeries.Panel1()
      ]),
    ],
    panelWidth=24,
  )
  +
  g.util.grid.makeGrid(
      [
        row.new("Row 2")
        + row.withPanels([
          panels.timeSeries.panel2(),
       ...
     ],
      panelWidth=12,
)
```

As you rightly mentioned, @Duologic, it does end up setting the row panel's `gridPos` to `"y": 0` is generated twice, when I think it should be (if row/panel heights are configured to 1 and 8 respectively):
```
"y": 0
...
"y": 9
```

So it looks like:

<img width="887" alt="Screenshot 2023-06-26 at 2 40 28 pm" src="https://github.com/grafana/grafonnet/assets/26584478/cdd4a87c-3d85-4044-a40a-e0b3445eeec1">

Fortunately, the first panel doesn't _have_ to be in a row, so I've removed the first row and it works fine for now. 

However, it would be nice to have more flexibility here, perhaps being able to define per-row panel widths?

**Comment by Duologic** [comment]
Thanks for this feedback, we've been thinking about a way to provide different grid or layout "strategies", but it's early so might take some time to land that.

**Comment by v-zhuravlev** [comment]
Small fix suggested here would allow to run makeGrid more than once:
https://github.com/grafana/grafonnet/pull/109

**Comment by v-zhuravlev** [comment]
Another grid strategy (wrapPanels) was merged here: #110

**Comment by Duologic** [comment]
Docs here: https://grafana.github.io/grafonnet/API/util.html#obj-grid

**Comment by Duologic** [comment]
There are now two grid strategies, I'd suggest opening up new issues for additional grid strategies.
